[Variables]

MainLightBlue=0,255,255
MainDarkBlue=0,102,102
MainPink=255,0,255
MainViolet=102,0,102
MainRed=255,0,0
MainDarkRed=102,0,0
MainGreen=0,255,0
MainDarkGreen=0,102,0

CurrentMainColor=0,255,255

SecondaryLightBlue=0,255,255
SecondaryDarkBlue=0,102,102
SecondaryPink=204,0,204
SecondaryViolet=102,0,102
SecondaryRed=255,0,0
SecondaryDarkRed=102,0,0
SecondaryGreen=0,255,0
SecondaryDarkGreen=0,102,0

CurrentSecondaryColor=0,102,102

BottonLightBlue=0,255,255
BottonDarkBlue=0,102,102
BottonPink=204,0,204
BottonViolet=102,0,102
BottonRed=255,0,0
BottonDarkRed=102,0,0
BottonGreen=0,255,0
BottonDarkGreen=0,102,0

CurrentBottonColor=0,102,102

##CurrentFontFace=Segoe WP Light##
CurrentFontFace=Courier Regular
AlbumSize=0,255,255
