[Variables]
PlayerPath=C:\Users\Mylbp2ps3\AppData\Roaming\Spotify\spotify.exe


MainLightBlue=0,255,255
MainDarkBlue=0,102,102
MainPink=255,0,255
MainViolet=102,0,102
MainRed=255,0,0
MainDarkRed=102,0,0
MainGreen=0,255,0
MainDarkGreen=0,102,0

CurrentMainColor=255,255,255

SecondaryLightBlue=0,255,255
SecondaryDarkBlue=0,102,102
SecondaryPink=204,0,204
SecondaryViolet=102,0,102
SecondaryRed=255,0,0
SecondaryDarkRed=102,0,0
SecondaryGreen=0,255,0
SecondaryDarkGreen=0,102,0

CurrentSecondaryColor=107,106,106

BottomLightBlue=0,255,255
BottomDarkBlue=0,102,102
BottomPink=204,0,204
BottomViolet=102,0,102
BottomRed=255,0,0
BottomDarkRed=102,0,0
BottomGreen=0,255,0
BottomDarkGreen=0,102,0

CurrentBottomColor=#BottomLightBlue#

##CurrentFontFace=Segoe WP Light##
CurrentFontFace=Courier Regular
